/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWearablesRouteImport } from './routes/_app/wearables'
import { Route as AppSosRouteImport } from './routes/_app/sos'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRecordsRouteImport } from './routes/_app/records'
import { Route as AppQrCodeRouteImport } from './routes/_app/qr-code'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppHospitalsRouteImport } from './routes/_app/hospitals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiInsightsRouteImport } from './routes/_app/ai-insights'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWearablesRoute = AppWearablesRouteImport.update({
  id: '/wearables',
  path: '/wearables',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppQrCodeRoute = AppQrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsRoute = AppHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hospitals': typeof AppHospitalsRoute
  '/profile': typeof AppProfileRoute
  '/qr-code': typeof AppQrCodeRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/sos': typeof AppSosRoute
  '/wearables': typeof AppWearablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/ai-insights': typeof AppAiInsightsRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/hospitals': typeof AppHospitalsRoute
  '/profile': typeof AppProfileRoute
  '/qr-code': typeof AppQrCodeRoute
  '/records': typeof AppRecordsRoute
  '/settings': typeof AppSettingsRoute
  '/sos': typeof AppSosRoute
  '/wearables': typeof AppWearablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/ai-insights': typeof AppAiInsightsRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/hospitals': typeof AppHospitalsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/qr-code': typeof AppQrCodeRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sos': typeof AppSosRoute
  '/_app/wearables': typeof AppWearablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/ai-insights'
    | '/analytics'
    | '/dashboard'
    | '/hospitals'
    | '/profile'
    | '/qr-code'
    | '/records'
    | '/settings'
    | '/sos'
    | '/wearables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/ai-insights'
    | '/analytics'
    | '/dashboard'
    | '/hospitals'
    | '/profile'
    | '/qr-code'
    | '/records'
    | '/settings'
    | '/sos'
    | '/wearables'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/ai-insights'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/hospitals'
    | '/_app/profile'
    | '/_app/qr-code'
    | '/_app/records'
    | '/_app/settings'
    | '/_app/sos'
    | '/_app/wearables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wearables': {
      id: '/_app/wearables'
      path: '/wearables'
      fullPath: '/wearables'
      preLoaderRoute: typeof AppWearablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sos': {
      id: '/_app/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr-code': {
      id: '/_app/qr-code'
      path: '/qr-code'
      fullPath: '/qr-code'
      preLoaderRoute: typeof AppQrCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospitals': {
      id: '/_app/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AppHospitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-insights': {
      id: '/_app/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHospitalsRoute: typeof AppHospitalsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQrCodeRoute: typeof AppQrCodeRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSosRoute: typeof AppSosRoute
  AppWearablesRoute: typeof AppWearablesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHospitalsRoute: AppHospitalsRoute,
  AppProfileRoute: AppProfileRoute,
  AppQrCodeRoute: AppQrCodeRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSosRoute: AppSosRoute,
  AppWearablesRoute: AppWearablesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
